// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSA_Final_Project.Models;

#nullable disable

namespace WSA_Final_Project.Migrations
{
    [DbContext(typeof(WSAFinalContext))]
    partial class WSAFinalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WSA_Final_Project.Models.Filament", b =>
                {
                    b.Property<int>("FilamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilamentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilamentId");

                    b.ToTable("Filaments");

                    b.HasData(
                        new
                        {
                            FilamentId = 1,
                            Description = "PLA is a biodegradable thermoplastic derived from renewable resources like corn starch or sugarcane. It is one of the most commonly used filaments in 3D printing due to its ease of use, low warping, and wide availability. PLA is ideal for beginners and is suitable for a variety of applications, including prototypes, models, and decorative items.",
                            Material = "PLA",
                            MaterialFull = "Polylactic Acid"
                        },
                        new
                        {
                            FilamentId = 2,
                            Description = "ABS is a strong and durable thermoplastic that is commonly used in 3D printing. It is known for its toughness, impact resistance, and ability to withstand higher temperatures compared to PLA. ABS is often used for functional parts, mechanical components, and objects that require strength and durability. However, it can be more challenging to print with due to its tendency to warp and emit fumes during printing.",
                            Material = "ABS",
                            MaterialFull = "Acrylonitrile Butadiene Styrene"
                        },
                        new
                        {
                            FilamentId = 3,
                            Description = "PETG is a popular filament that combines the ease of use of PLA with the strength and durability of ABS. It is known for its excellent layer adhesion, low warping, and resistance to moisture. PETG is often used for functional parts, mechanical components, and objects that require strength and durability. It is also food-safe and can be used for applications such as water bottles and food containers.",
                            Material = "PETG",
                            MaterialFull = "Polyethylene Terephthalate Glycol"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
